spring.application.name=taskflow

#datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
spring.datasource.username=postgres
spring.datasource.password=root

#JPA/hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.open-in-view=false

#JWT
jwt.secret=4a1d8c3b5f7e9a2d6c8f1b3e5a7d9c2f4e6b8a1d3c5f7e9a2b4d6f8c1e3a5b7
jwt.expiration=86400000